#!/usr/bin/env bash
#
# bootstrap: script to download all of the required scripts & run a recipe
#
#    set the RECIPE environment variable to the recipe you want to run.
#
#    usage: bootstrapper
#
#
#   Copyright (c) 2017 Chris Obbard <chris@64studio.com>
#


# remove temporary folder if we have already run before
rm -rf /tmp/cloudhelper

# get the latest code
wget https://github.com/64studio/cdd-sel/archive/master.zip
unzip master.zip

# go into the directory
cd /tmp/cloudhelper

# run the recipe
./recipes/$RECIPE