#!/usr/bin/env bash
#
# bootstrap: script to download all of the required scripts & run a recipe
#
#    set the RECIPE environment variable to the recipe you want to run.
#
#    usage: bootstrap <recipe>
#
#
#   Copyright (c) 2017 Chris Obbard <chris@64studio.com>
#

# read in the args
RECIPE=$1

# remove temporary folder if we have already run before
rm -rf /tmp/cloudhelper-master

# install dependencies
apt-get update
apt-get install unzip wget --yes

# move to the system temporary folder
cd /tmp

# get the latest code
wget https://github.com/64studio/cloudhelper/archive/master.zip
unzip master.zip

# go into the directory
cd /tmp/cloudhelper-master

# run the recipe
./recipes/$RECIPE