#cloud-config

#
# change the recipe variable in the script below.
#

runcmd:
 - wget https://raw.githubusercontent.com/64studio/cloudhelper/master/bootstrap/bootstrap
 - chmod +x bootstrap
 - ./bootstrap "stretch_setup"