#!/usr/bin/env bash
#
# secure_ssh: secures OpenSSH
#
#    disables root ssh logins
#
#    usage: secure_ssh
#
#
#   Copyright (c) 2017 Chris Obbard <chris@64studio.com>
#



# set PermitRootLogin no
sed -i "s|[#]*PermitRootLogin.*|PermitRootLogin no|g" "/etc/ssh/sshd_config"

# set ChallengeResponseAuthentication no
sed -i "s|[#]*ChallengeResponseAuthentication.*|ChallengeResponseAuthentication no|g" "/etc/ssh/sshd_config"

# set PasswordAuthentication no
sed -i "s|[#]*PasswordAuthentication.*|PasswordAuthentication no|g" "/etc/ssh/sshd_config"

# set UsePAM no
sed -i "s|[#]*UsePAM.*|UsePAM no|g" "/etc/ssh/sshd_config"


# restart the sshd service
systemctl restart sshd.service
